bot_uin: '1639950290'
root: '3077906125'
debug: false
adapters:
- type: napcat
  platform: qq
  enabled: true
  config:
    ws_uri: ws://192.168.31.39:3001
    ws_token: '114514'
    webui_uri: http://192.168.31.39:6099
    webui_token: db3f00ce939e
    enable_webui: true
plugin:
  plugins_dir: plugins
  load_plugin: true
  plugin_whitelist: []
  plugin_blacklist: []
